/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/common/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/page/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [,
    "bg-white",
    "bg-black",
    "bg-orangeMain",
    "bg-skyMain",
    "bg-violetMain",
    "bg-redMain",
    "bg-primary",
    "bg-primarygrey",
    "bg-green-100",
    " text-green-700",
    "bg-background",
    "bg-modelgrey",
    "bg-orangeSecondary",
    "bg-skySecondary",
    "bg-violetSecondary",
    "bg-redSecondary",
    "bg-orangePrimary",
    "bg-skyPrimary",
    "bg-violetPrimary",
    "bg-redPrimary",
    "text-white",
    "text-black",
    "text-orangeMain",
    "text-skyMain",
    "text-violetMain",
    "text-redMain",
    "text-primary",
    "text-primarygrey",
    "text-background",
    "text-modelgrey",
    "text-orangeSecondary",
    "text-skySecondary",
    "text-violetSecondary",
    "text-redSecondary",
    "text-orangePrimary",
    "text-skyPrimary",
    "text-violetPrimary",
    "text-redPrimary",
    "border-transparent"
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
    colors: {
      white: "#ffffff",
      black: "#333333",
      orangeMain: "#FFA901",
      skyMain: "#24A8FA",
      violetMain: "#7A6EFE",
      redMain: "#FF5363",
      primary: "#7C7F84",
      primarygrey: "#EBEFF2",
      background: "#F9F9F9",
      modelgrey: "#3d3d3de0",
      orangeSecondary: "#FFB72D",
      skySecondary: "#4BB8F9",
      violetSecondary: "#9287FE",
      redSecondary: "#FF717E",
      orangePrimary: "#FFF9E9",
      skyPrimary: "#E9F6FE",
      violetPrimary: "#F2F2FE",
      redPrimary: "#FEEEEF",
    },
  },
  plugins: [],
};
