import "./globals.css";
import type { Metadata } from "next";
import Nav from "@/components/navbar";
import SearchBar from '@/components/searchbar'
import { redirect } from 'next/navigation'
 
export async function getServerSideProps(context: any) {
  if (context.req) {
      redirect("/overview");

  }
}

export const metadata: Metadata = {
  title: "HMS Hub",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div className="bg-background min-h-[100vh] p-4 md:ml-72">
          <div className="sm:container-lg md:mx-auto">
          <div className="mx-4 z-[5] sticky"><SearchBar /></div>
          <div className="px-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
